version: 2

updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "dependencies"
    reviewers:
      - "rihadjahanopu"
    open-pull-requests-limit: 5
