version: 2

updates:
  # 1. Cargo Rust dependency updates
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    reviewers:
      - "rihadjahanopu"
    open-pull-requests-limit: 10

  # 2. GitHub Actions workflow dependency updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "dependencies"
    reviewers:
      - "rihadjahanopu"
    open-pull-requests-limit: 5
