// ============================================================================
// STATUS: 100% NATIVE RUST & BULLETPROOF (ZERO EXTERNAL BINARY DEPENDENCIES)
// AUDIT COMPLETED: FULL FEATURE PARITY, CROSS-OS VERIFIED & OPTIMIZED
// HANDS-OFF GUARANTEE: NO MANUAL EDITS REQUIRED
// ============================================================================

// =============================================================================
//  src/init/mod.rs — Cross-shell bootstrap code generator

//
//  `fancybash init <shell>` pipes the output of this module into the running
//  shell (e.g. `eval "$(fancybash init zsh)"`).
//
//  Generated code responsibilities:
//    1. Export canonical environment variables.
//    2. Prepend canonical PATH entries.
//    3. Load all aliases for the target shell.
//    4. Wire the prompt hook (PROMPT_COMMAND / precmd / fish_prompt / prompt).
//    5. Wire the pre-execution hook for cmd-duration tracking.
//    6. Load shell-specific plugin stubs (completion, autosuggestions, etc.).
// =============================================================================

pub mod bash;
pub mod cleaner;
pub mod fish;
pub mod pwsh;
pub mod shared;
pub mod zsh;

/// Dispatch table: map shell name → generator function.
pub fn generate(shell: &str) -> Result<String, String> {
    match shell.to_ascii_lowercase().as_str() {
        "bash" => Ok(bash::generate()),
        "zsh"  => Ok(zsh::generate()),
        "fish" => Ok(fish::generate()),
        "pwsh" | "powershell" => Ok(pwsh::generate()),
        other => Err(format!(
            "unsupported shell: '{other}'. \
             Supported: bash, zsh, fish, pwsh (powershell)"
        )),
    }
}

// ── Shared header / footer helpers ───────────────────────────────────────────

pub(crate) fn fancybash_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// Emit a shell-comment block describing the generated file's origin.
pub(crate) fn header_comment(comment_char: &str) -> String {
    format!(
        "{cc} ─────────────────────────────────────────────────────────────\n\
         {cc}  fancybash — generated by `fancybash init` v{ver}\n\
         {cc}  DO NOT EDIT — re-run `eval \"$(fancybash init <shell>)\"` to update.\n\
         {cc} ─────────────────────────────────────────────────────────────\n",
        cc = comment_char,
        ver = fancybash_version()
    )
}
